# Generated by Django 4.2.11 on 2024-05-14 10:15

import courseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=courseapp.models.save_tbn_vids),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=courseapp.models.save_tbn_vids),
        ),
    ]
