# Generated by Django 4.2.11 on 2024-05-20 07:11

import courseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseapp', '0003_enrollment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(default=courseapp.models.pk_generator, primary_key=True, serialize=False),
        ),
    ]
